version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306'
    expose:
      - '3306'
    volumes:
      - ./data-wordpress/sql:/var/lib/mysql
  web1:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./data-wordpress/html:/var/www/html
    ports:
      - "80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      
  haproxy:
    image: eeacms/haproxy
    depends_on:
    - "web1"
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "web1"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"


